[server]
headless = false
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#8B5CF6"
backgroundColor = "#0b0f19"
secondaryBackgroundColor = "#161e31"
textColor = "#f8fafc"
font = "sans serif"
